#! /bin/sh

# Resolve Python executable path
DL_TARGET_PYTHON="$(which python)"
# Redirect Python in base environment to cluster environment
if [ "${DL_TARGET_PYTHON}" = "${DL_SHARED_DIR}/conda/bin/python" ]; then
    DL_TARGET_PYTHON="${DL_SHARED_DIR}/envs/templates/${DL_CLUSTER_ENV}/bin/python"
fi

# Execute Python
exec "${DL_TARGET_PYTHON}" "$@"